top_100_gdp_countries = {
    "United States": "USA",
    "China": "CHN",
    "Japan": "JPN",
    "Germany": "DEU",
    "India": "IND",
    "United Kingdom": "GBR",
    "France": "FRA",
    "Canada": "CAN",
    "Italy": "ITA",
    "Brazil": "BRA",
    "South Korea": "KOR",
    "Russia": "RUS",
    "Australia": "AUS",
    "Spain": "ESP",
    "Mexico": "MEX",
    "Indonesia": "IDN",
    "Netherlands": "NLD",
    "Saudi Arabia": "SAU",
    "Turkey": "TUR",
    "Switzerland": "CHE",
    "Taiwan": "TWN",
    "Poland": "POL",
    "Sweden": "SWE",
    "Belgium": "BEL",
    "Thailand": "THA",
    "Argentina": "ARG",
    "Nigeria": "NGA",
    "Austria": "AUT",
    "Iran": "IRN",
    "Norway": "NOR",
    "United Arab Emirates": "ARE",
    "Israel": "ISR",
    "South Africa": "ZAF",
    "Ireland": "IRL",
    "Denmark": "DNK",
    "Singapore": "SGP",
    "Malaysia": "MYS",
    "Philippines": "PHL",
    "Colombia": "COL",
    "Bangladesh": "BGD",
    "Vietnam": "VNM",
    "Pakistan": "PAK",
    "Chile": "CHL",
    "Finland": "FIN",
    "Egypt": "EGY",
    "Czech Republic": "CZE",
    "Romania": "ROU",
    "Portugal": "PRT",
    "Iraq": "IRQ",
    "New Zealand": "NZL",
    "Peru": "PER",
    "Greece": "GRC",
    "Kazakhstan": "KAZ",
    "Qatar": "QAT",
    "Hungary": "HUN",
    "Kuwait": "KWT",
    "Ukraine": "UKR",
    "Morocco": "MAR",
    "Slovakia": "SVK",
    "Ecuador": "ECU",
    "Angola": "AGO",
    "Sri Lanka": "LKA",
    "Ethiopia": "ETH",
    "Kenya": "KEN",
    "Dominican Republic": "DOM",
    "Oman": "OMN",
    "Guatemala": "GTM",
    "Luxembourg": "LUX",
    "Bulgaria": "BGR",
    "Panama": "PAN",
    "Uruguay": "URY",
    "Costa Rica": "CRI",
    "Croatia": "HRV",
    "Belarus": "BLR",
    "Slovenia": "SVN",
    "Lithuania": "LTU",
    "Serbia": "SRB",
    "Azerbaijan": "AZE",
    "Uzbekistan": "UZB",
    "Myanmar": "MMR",
    "Jordan": "JOR",
    "Turkmenistan": "TKM",
    "Democratic Republic of the Congo": "COD",
    "Latvia": "LVA",
    "Bahrain": "BHR",
    "Paraguay": "PRY",
    "Estonia": "EST",
    "Bolivia": "BOL",
    "Nepal": "NPL",
    "Iceland": "ISL",
    "Trinidad and Tobago": "TTO",
    "El Salvador": "SLV",
    "Honduras": "HND",
    "Cyprus": "CYP",
    "Bosnia and Herzegovina": "BIH",
    "Cambodia": "KHM",
    "Georgia": "GEO",
    "Mongolia": "MNG",
    "Albania": "ALB",
    "Armenia": "ARM",
    "Namibia": "NAM",
    "Botswana": "BWA",
    "Brunei": "BRN",
    "Jamaica": "JAM"
}
